name: compositional_jailbreaking
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy==2.3.1
      - pandas==2.3.0
      - matplotlib==3.10.3
      - seaborn==0.13.2
      - scipy==1.16.0
      - scikit-learn==1.7.0
      - openai==1.88.0
      - requests==2.34.2
      - PyYAML==6.0.2
